language: php
sudo: false
php:
  - nightly
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
matrix:
  fast_finish: true
  allow_failures:
    - php:
        - 7.3
        - nightly
script:
  - umask 0022
  - sh scripts/pear.sh run-tests -q -d -r tests
  - sh scripts/pear.sh package-validate package2.xml
  - sh scripts/pear.sh package package2.xml
  - sh scripts/pear.sh package-validate PEAR-*.tgz
  - pear install --force package2.xml
  - pear list
  - pear install --force PEAR-*.tgz
  - pear list
  - pear upgrade --force archive_tar console_getopt structures_graph xml_util
  - pear list
  - sh scripts/pear.sh run-tests -q -d -r tests
  - pear install --force php_archive
  - pear list
  - ./build-release.sh
