language: php
sudo: false
php:
  - nightly
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
matrix:
  fast_finish: true
  allow_failures:
    - php:
        - 7.3
        - nightly
script:
  - umask 0022
  - sh scripts/pear.sh run-tests -q -d -r tests
